# Site settings
title: Sakke's Blog
email: tamsna_sakhr@yahoo.fr
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog where I share my thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sakke82.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Permalink structure
permalink: /:year/:month/:day/:title/

# Time zone
timezone: UTC
